### ISSUE TITLE
Handle metadata file not named "metadata.csv"

### ISSUE THREAD

**Issue by gecron** [SciencesPoDRIS/iamassaccess#24]
Any name for metadata except "metadata.csv" generates an error

Traceback (most recent call last):
  File "iamassaccess.py", line 219, in <module>
    updateItems(args.metadata)
  File "iamassaccess.py", line 143, in updateItems
    metadata = load_csv_metadata_file(metadata_file)
  File "iamassaccess.py", line 108, in load_csv_metadata_file
    value = unicode(attributes[i],"utf-8")
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 16: invalid continuation byte

**Comment by annelhote** [comment]
It seems not be linked to the file's name but to the file's content encoding. Please link the file to the issue.
